apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" $ }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: {{ template "name" $ }}-cert
      hosts:      
      - {{ .Values.domain }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}-service
          servicePort: 80