apiVersion: v1
kind: Service

metadata:
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "name" . }}-service

spec:
  selector:
    app: {{ template "name" . }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080