apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
data:
  nginx.conf: |
    events {}
    error_log /var/log/nginx/error.log info;
    access_log /var/log/nginx/access.log;
    http {
      server {

        # Set nginx to serve files from the shared volume!
        root /var/www/html;

        listen 80 default_server;
        listen [::]:80 default_server;
        
        # config for random data file
        location /random.data.100 {
          sendfile off;
          tcp_nopush on;
          add_header Last-Modified $date_gmt;
          add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
          if_modified_since off;
          expires off;
          etag off;
        }

        # set listener for php files
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
          client_max_body_size 50M;
        }
        
        server_name _;

        # 404 Catch
        location / {
          try_files $uri $uri/ index.html =404;
        }
        
      }
    }