apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" $ }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ template "name" . }}-service
          servicePort: 80