apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" $ }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/server-alias: pin-reset.fastpbx.io
spec:
  tls:
    - secretName: {{ template "name" $ }}-alias-cert
      hosts:      
      - pin-reset.fastpbx.io
    - secretName: {{ template "name" $ }}-cert
      hosts:      
      - {{ .Values.domain }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ template "name" . }}-service
          servicePort: 80
  - host: "pin-reset.fastpbx.io"
    http:
      paths:
      - backend:
          serviceName: {{ template "name" . }}-service
          servicePort: 80