apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" $ }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - secretName: {{ template "name" $ }}-alias-cert
      hosts:      
      - {{ .Values.alias }}
    - secretName: {{ template "name" $ }}-cert
      hosts:      
      - {{ .Values.domain }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ template "name" . }}-service
          servicePort: 80
  - host: {{ .Values.alias }}
    http:
      paths:
      - backend:
          serviceName: {{ template "name" . }}-service
          servicePort: 80