apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-service
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 9000
  selector:
    app: {{ template "fullname" . }}