apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: heplify-server
  name: heplify-server
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "9060"
    port: 9060
    targetPort: 9060
  - name: 9060-udp
    port: 9060
    protocol: UDP
    targetPort: 9060
  selector:
    io.kompose.service: heplify-server
status:
  loadBalancer: {}
