apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ template "name" . }}-asterisk-deployment
  labels:
    component: {{ template "name" . }}-asterisk
    release: "{{ .Release.Name }}"

spec:

  replicas: {{ .Values.astreplicas }}

  selector:  
    matchLabels:
      component: {{ template "name" . }}-asterisk

  template:

    metadata:
      labels:
        component: {{ template "name" . }}-asterisk
        release: "{{ .Release.Name }}"

    spec:

      imagePullSecrets:
        - name: fastpbxdockernexus

      volumes:
        - name: config
          emptyDir: {}

      containers:

        - name: asterisk
          image: docker.nexus3.fastpbx.io/asterisk:0.1
          volumeMounts:
            - name: config
              mountPath: /etc/asterisk

        - name: config
          image: {{ .Values.astimage }}
          env:
            - name: CLOUD
              value: {{ .Values.cloud }}
            - name: CORE_PATH
              value: {{ .Values.asteriskConfigUrl}}
            - name: OUTPUT_DIR
              value: {{ .Values.asteriskConfigDir}}
            - name: RERENDER_ACTION
              value: {{ .Values.asteriskConfigRenderAction}}
          command:
            - /app
          volumeMounts:
            - name: config
              mountPath: /etc/asterisk