apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: {{ template "name" . }}-kamailio-daemonset
  labels:
    component: {{ template "name" . }}-kamailio
    release: "{{ .Release.Name }}"

spec:

  selector:
    matchLabels:
      component: {{ template "name" . }}-kamailio
      
  template:

    metadata:
      name: {{ template "name" . }}-kamailio
      labels:
        component: {{ template "name" . }}-kamailio
        release: "{{ .Release.Name }}"
        
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: fastpbx.io/siprole
                operator: In
                values:
                - {{ .Values.siprole }}

      imagePullSecrets:
        - name: fastpbxdockernexus

      hostNetwork: true

      volumes:
        - name: config

      containers:

        - name: kamailio
          image: docker.nexus3.fastpbx.io/kamailio:0.1
          volumeMounts:
            - name: config
              mountPath: /data/kamailio
          env:
            - name: CLOUD
              value: {{ .Values.cloud }}

        - name: rtpproxy
          image: docker.nexus3.fastpbx.io/rtpproxy:0.1
          env:
            - name: CLOUD
              value: {{ .Values.cloud }}

        - name: loadconfig
          image: docker.nexus3.fastpbx.io/k8s-load-config:0.1
          env:
            - name: CORE_PATH
              value: https://github.com/FastPBX/scratch/releases/download/v0.1/config.zip
            - name: OUTPUT_DIR
              value: "/data/kamailio"
            - name: RERENDER_ACTION
              value: "/bin/bash"
          volumeMounts:
            - name: config
              mountPath: /data/kamailio

        - name: dispatchers
          image: docker.nexus3.fastpbx.io/dispatchers:0.1
          command:
            - /app
            - "-set"
            - {{ printf "%s:%s-asterisk-service=1:5080" .Release.Namespace .Release.Name }}
          volumeMounts:
            - name: config
              mountPath: /data/kamailio