apiVersion: v1
kind: Service

metadata:
  name: {{ template "name" . }}-kamailio-service
  labels:
    component: {{ template "name" . }}-kamailio
    release: "{{ .Release.Name }}"

spec:

  selector:
    component: {{ template "name" . }}-kamailio

  ports:
    - name: sip
      protocol: UDP
      port: 5060
      targetPort: 5060

