apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: {{ template "name" . }}-kamailio-daemonset
  labels:
    component: {{ template "name" . }}-kamailio
    release: "{{ .Release.Name }}"

spec:

  selector:
    matchLabels:
      component: {{ template "name" . }}-kamailio
      
  template:

    metadata:
      name: {{ template "name" . }}-kamailio
      labels:
        component: {{ template "name" . }}-kamailio
        release: "{{ .Release.Name }}"
        
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: fastpbx.io/siprole
                operator: In
                values:
                - {{ .Values.siprole }}

      imagePullSecrets:
        - name: fastpbxdockernexus

      hostNetwork: true

      volumes:
        - name: config

      containers:

        - name: kamailio
          image: {{ .Values.kamDockerImage }}
          volumeMounts:
            - name: config
              mountPath: /etc/kamailio
          env:
            - name: CLOUD
              value: {{ .Values.cloud }}

        - name: rtpproxy
          image: docker.nexus3.fastpbx.io/rtpproxy:0.1
          env:
            - name: CLOUD
              value: {{ .Values.cloud }}

        - name: loadconfig
          image: {{ .Values.kamCfgImage }}
          env:
            - name: CORE_PATH
              value: {{ .Values.kamCfgCorePath }}
            - name: OUTPUT_DIR
              value: "/etc/kamailio"
            - name: RERENDER_ACTION
              value: {{ .Values.kamCfgRenderAction }}
          volumeMounts:
            - name: config
              mountPath: /etc/kamailio
        