kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: voip-manager
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods","endpoints","services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list", "update", "patch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manager
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: User
    name: {{ printf "system:serviceaccount:%s:default" .Release.Namespace }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: voip-manager
  apiGroup: rbac.authorization.k8s.io
