apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ template "name" . }}-deployment
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    
spec:

  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: "{{ .Release.Name }}"

  template:

    metadata:
      labels:
        app: {{ template "name" . }}
        release: "{{ .Release.Name }}"

    spec:

      # Create Shared Volume For Source Code
      volumes:
        - name: shared-volume
          emptyDir: {}

      # Clone Source Code Repo Into Shared Volume
      initContainers:
        - name: {{ template "name" . }}-setup
          image: alpine/git
          volumeMounts:
            - name: shared-volume
              mountPath: /opt/app
          args:
            - clone
            - --single-branch
            - --
            - https://github.com/FastPBX/pbxlink-tester.git
            - /opt/app
        - name: {{ template "name" . }}-install
          image: node:alpine
          volumeMounts:
            - name: shared-volume
              mountPath: /opt/app
          workingDir: /opt/app
          args: ["yarn"]

      # Launch Node App From Shared Source Code In Shared Volume
      containers:
        - name: {{ template "name" . }}-app
          image: node:alpine
          volumeMounts:
            - name: shared-volume
              mountPath: /opt/app
          envFrom:
            - configMapRef:
              name: pbxlink-tester
            - secretRef:
              name: pbxlink-tester-secrets
          command: ["/bin/sh"]
          args: ["-c","node /opt/app/dist/server.js"]
          ports:
            - name: "http"
              containerPort: 3000