apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: theapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
      - test.mrclusia.com
      secretName: letsencrypt-issuer-account-key
  rules:
  - host: {{ .Values.domain | quote }}
    http:
      paths:
      - backend:
          serviceName: theapp
          servicePort: 80