apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: theapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.domain | quote }}
    http:
      paths:
      - backend:
          serviceName: theapp
          servicePort: 80