apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: {{ .Release.Name | quote }}-issuer
spec:
  tls:
    - hosts:
      - {{ .Values.domain | quote }}
      secretName: {{ .Release.Name | quote }}-cert
  rules:
  - host: {{ .Values.domain | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}-service
          servicePort: 80