apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-service
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "name" . }}
  ports:
  - name: "55510"
    port: 55510
    targetPort: 55510
    protocol: UDP